from fpdf import FPDF
from fpdf.enums import XPos, YPos

def create_clinical_report_pdf(data):
    pdf = FPDF()
    pdf.set_margins(10, 10, 10)
    pdf.add_page()
    
    # Header background
    pdf.set_fill_color(30, 42, 74)
    pdf.rect(0, 0, 210, 40, 'F')
    pdf.set_font("helvetica", "B", 24)
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(10, 5)
    pdf.cell(190, 15, "NEURAL SCREENING SYSTEM", new_x=XPos.LMARGIN, new_y=YPos.NEXT, align='C')
    pdf.set_font("helvetica", "", 12)
    pdf.set_xy(10, 25)
    pdf.cell(190, 10, "Clinical Diagnostic Report | Confidential", new_x=XPos.LMARGIN, new_y=YPos.NEXT, align='C')
    
    pdf.ln(15)
    pdf.set_text_color(0, 0, 0)
    
    pdf.set_font("helvetica", "B", 16)
    pdf.set_x(10)
    pdf.cell(190, 10, "1. Patient Intelligence Summary", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("helvetica", "", 12)
    pdf.set_x(10)
    pdf.cell(190, 10, f"Timestamp: {data['timestamp']}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    pdf.ln(3)
    score = data['final_score']
    pdf.set_font("helvetica", "B", 14)
    pdf.set_x(10)
    pdf.cell(190, 10, f"Global Cognitive Index: {score:.0%}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    bar_y = pdf.get_y()
    pdf.set_draw_color(200, 200, 200)
    pdf.rect(10, bar_y, 190, 8)
    fill_w = 190 * score
    pdf.set_fill_color(34, 197, 94) if score < 0.35 else pdf.set_fill_color(239, 68, 68)
    if fill_w > 0:
        pdf.rect(10, bar_y, fill_w, 8, 'F')
    pdf.ln(14)
    
    pdf.set_font("helvetica", "B", 14)
    pdf.set_x(10)
    pdf.cell(190, 10, "2. Domain-Specific Assessment", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("helvetica", "B", 11)
    pdf.set_fill_color(240, 240, 240)
    pdf.set_x(10)
    pdf.cell(95, 9, "Cognitive Domain", border=1, new_x=XPos.RIGHT, new_y=YPos.TOP, align='C', fill=True)
    pdf.cell(95, 9, "Risk / Score", border=1, new_x=XPos.LMARGIN, new_y=YPos.NEXT, align='C', fill=True)
    
    pdf.set_font("helvetica", "", 11)
    domains = [
        ("Speech Biomarkers", f"{data['speech_risk']:.0%}"),
        ("Linguistic Complexity", f"{data['text_risk']:.0%}"),
        ("Short-term Memory", f"{data['memory_score']:.0%} (Accuracy)"),
        ("Articulation Precision", f"{data['pronunciation_score']:.0%} (Similarity)")
    ]
    for domain, val in domains:
        pdf.set_x(10)
        pdf.cell(95, 9, domain, border=1, new_x=XPos.RIGHT, new_y=YPos.TOP)
        pdf.cell(95, 9, val, border=1, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    pdf.ln(5)
    pdf.set_font("helvetica", "B", 14)
    pdf.set_x(10)
    pdf.cell(190, 10, "3. Neural Biomarker Findings", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("helvetica", "", 11)
    for finding in data['findings']:
        pdf.set_x(10)
        pdf.multi_cell(190, 8, f"  - {finding}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    pdf.ln(5)
    pdf.set_x(10)
    if score >= 0.35:
        pdf.set_fill_color(255, 220, 220)
    else:
        pdf.set_fill_color(220, 255, 220)
    pdf.set_font("helvetica", "B", 14)
    status = "FOLLOW-UP RECOMMENDED" if score >= 0.35 else "NORMAL STABILITY"
    pdf.cell(190, 14, f"Clinical Status: {status}", border=1, new_x=XPos.LMARGIN, new_y=YPos.NEXT, align='C', fill=True)
    
    pdf.ln(8)
    pdf.set_x(10)
    pdf.set_font("helvetica", "I", 9)
    pdf.multi_cell(190, 5,
        "DISCLAIMER: This report is generated by an experimental AI biomarker system. "
        "Results are probabilistic and MUST be validated by a licensed neurologist or "
        "speech pathologist. Not for diagnostic use.",
        new_x=XPos.LMARGIN, new_y=YPos.NEXT
    )
    
    return bytes(pdf.output())


test_data = {
    'timestamp': '2026-03-05 22:00',
    'final_score': 0.55,
    'speech_risk': 0.6,
    'text_risk': 0.5,
    'memory_score': 0.7,
    'pronunciation_score': 0.65,
    'findings': [
        'Aphasic Hesitation (Non-fluency)',
        'Palilalia (Speech Perseveration)',
        'Reduced lexical diversity detected'
    ]
}

result = create_clinical_report_pdf(test_data)
print(f"Type: {type(result)}")
print(f"Size: {len(result)} bytes")
print(f"Starts with PDF header: {result[:4] == b'%PDF'}")

with open("test_report.pdf", "wb") as f:
    f.write(result)
print("Saved to test_report.pdf")
